services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: my_agent_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ..
      dockerfile: Docker/dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../src/.env
    depends_on:
      - postgres
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000

  gui:
    build:
      context: ..
      dockerfile: Docker/dockerfile
    ports:
      - "8501:8501"
    env_file:
      - ../src/.env
    depends_on:
      - postgres
    command: streamlit run gui/streamlit_app.py --server.address 0.0.0.0 --server.port 8501

volumes:
  postgres_data: